# Generated by Django 4.2.27 on 2025-12-07 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, help_text='Job title/Role', max_length=200, null=True)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-1000', '201-1000'), ('1000+', '1000+')], max_length=20, null=True)),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('education', 'Education'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('real_estate', 'Real Estate'), ('hospitality', 'Hospitality'), ('other', 'Other')], max_length=50, null=True)),
                ('use_case', models.TextField(blank=True, help_text='Use case/Interest description', null=True)),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('ad_campaign', 'Ad Campaign'), ('social_media', 'Social Media'), ('email_campaign', 'Email Campaign'), ('event', 'Event'), ('other', 'Other')], default='website', max_length=50)),
                ('referral_code', models.CharField(blank=True, max_length=100, null=True)),
                ('priority_score', models.IntegerField(default=0, help_text='Calculated priority score')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('invited', 'Invited'), ('onboarded', 'Onboarded'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('invite_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('expected_start_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes', null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
    ]
