"""
Django settings for sitebackend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-e(a)n*+(_-6%g3l_@$w+r1u_sjh$oawyaem6e5!0=+vh1a7(2)')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',  # API documentation
    'corsheaders',
    'django_ratelimit',
    'honeypot',
    'captcha',  # django-recaptcha
    'import_export',  # django-import-export
    'django_admin_listfilter_dropdown',  # Better dropdown filters
    'apps.contacts',
    'apps.waitlist',
    'apps.leads',
    'apps.newsletter',
    'apps.analytics',
    'apps.integrations',
    'apps.gdpr',
    'apps.webhooks',  # Webhook functionality
    'apps.ab_testing',  # A/B testing support
    'apps.core',  # Core utilities
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # i18n support
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.analytics.middleware.AnalyticsMiddleware',  # Analytics tracking
]

ROOT_URLCONF = 'sitebackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'apps' / 'integrations' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sitebackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='sitebackend_db'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='postgres'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# Initialize silenced system checks
SILENCED_SYSTEM_CHECKS = []

# Cache Configuration
REDIS_URL = config('REDIS_URL', default='')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'KEY_PREFIX': 'sitebackend',
            'TIMEOUT': 300,
        }
    }
else:
    # Use local memory cache in development
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'KEY_PREFIX': 'sitebackend',
            'TIMEOUT': 300,
        }
    }
    # Silence cache warnings in development (when using LocMemCache)
    SILENCED_SYSTEM_CHECKS.extend(['django_ratelimit.E003', 'django_ratelimit.W001'])


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = config('LANGUAGE_CODE', default='en-us')

TIME_ZONE = config('TIME_ZONE', default='UTC')

USE_I18N = config('USE_I18N', default=True, cast=bool)

USE_L10N = config('USE_L10N', default=True, cast=bool)

USE_TZ = config('USE_TZ', default=True, cast=bool)

# Supported languages
LANGUAGES = [
    ('en', 'English'),
    ('es', 'Spanish'),
    ('fr', 'French'),
    ('de', 'German'),
    ('it', 'Italian'),
    ('pt', 'Portuguese'),
    ('nl', 'Dutch'),
    ('pl', 'Polish'),
    ('ru', 'Russian'),
    ('ja', 'Japanese'),
    ('zh-hans', 'Simplified Chinese'),
    ('zh-hant', 'Traditional Chinese'),
]

# Locale paths
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = config('STATIC_ROOT', default=BASE_DIR / 'staticfiles')

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = config('MEDIA_ROOT', default=BASE_DIR / 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular Settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Site Backend API',
    'DESCRIPTION': 'Comprehensive Django REST Framework API for landing page and marketing website backend. Includes contact submissions, waitlist management, lead capture, newsletter subscriptions, analytics tracking, and GDPR compliance.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'TAGS': [
        {'name': 'Contacts', 'description': 'Contact form submissions and management'},
        {'name': 'Waitlist', 'description': 'Waitlist entry management'},
        {'name': 'Leads', 'description': 'Lead capture and management'},
        {'name': 'Newsletter', 'description': 'Newsletter subscription management'},
        {'name': 'Analytics', 'description': 'Page views, events, and conversion tracking'},
        {'name': 'GDPR', 'description': 'GDPR compliance endpoints (consent, data export, deletion)'},
    ],
    'CONTACT': {
        'name': 'API Support',
        'email': 'support@example.com',
    },
    'LICENSE': {
        'name': 'MIT License',
    },
    'SERVERS': [
        {
            'url': 'http://localhost:8000',
            'description': 'Development server'
        },
        {
            'url': 'https://api.example.com',
            'description': 'Production server'
        },
    ],
}

# CORS Configuration
# Allow frontend origin from monorepo
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# Multi-site support: Allow requests from multiple domains
# Default sites: oasys360.com, heals360.com, reliqo.app, vcsmy.com
DEFAULT_SITES = [
    'https://oasys360.com',
    'https://heals360.com',
    'https://reliqo.app',
    'https://vcsmy.com',
]

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default=','.join([FRONTEND_URL] + DEFAULT_SITES + ['http://localhost:3000', 'http://localhost:8000']),
    cast=Csv()
)
CORS_ALLOW_CREDENTIALS = True

# Login Configuration
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@example.com')
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# SMTP Configuration (used when EMAIL_BACKEND is smtp)
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Security Settings

# reCAPTCHA Configuration
RECAPTCHA_PUBLIC_KEY = config('RECAPTCHA_PUBLIC_KEY', default='')
RECAPTCHA_SECRET_KEY = config('RECAPTCHA_SECRET_KEY', default='')
RECAPTCHA_REQUIRED_SCORE = config('RECAPTCHA_REQUIRED_SCORE', default=0.5, cast=float)

# Silence reCAPTCHA test key warnings in development
SILENCED_SYSTEM_CHECKS.append('captcha.recaptcha_test_key_error')

# Rate Limiting Configuration
RATELIMIT_ENABLE = config('RATELIMIT_ENABLE', default=True, cast=bool)
RATELIMIT_USE_CACHE = config('RATELIMIT_USE_CACHE', default='default')

# Per-endpoint rate limits (configurable)
WAITLIST_RATE_LIMIT = config('WAITLIST_RATE_LIMIT', default='10/h')  # 10 requests per hour per IP
CONTACT_RATE_LIMIT = config('CONTACT_RATE_LIMIT', default='5/h')  # 5 requests per hour per IP
LEAD_RATE_LIMIT = config('LEAD_RATE_LIMIT', default='10/h')  # 10 requests per hour per IP

# Honeypot Configuration
HONEYPOT_FIELD_NAME = 'website'  # Field name for honeypot

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# CORS Additional Security
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Session Security
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)  # Set True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# CSRF Protection
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)  # Set True in production with HTTPS
CSRF_COOKIE_HTTPONLY = True
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# HTTPS Security (Production)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)  # Set True in production
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)  # Set to 31536000 (1 year) in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if config('SECURE_PROXY_SSL_HEADER', default=False, cast=bool) else None

# CRM Integration Configuration
CRM_PROVIDER = config('CRM_PROVIDER', default='')  # hubspot, salesforce, pipedrive
CRM_FIELD_MAPPING = {}  # JSON field mapping configuration

# HubSpot Configuration
HUBSPOT_API_KEY = config('HUBSPOT_API_KEY', default='')
HUBSPOT_ACCESS_TOKEN = config('HUBSPOT_ACCESS_TOKEN', default='')  # Alternative to API_KEY
HUBSPOT_PORTAL_ID = config('HUBSPOT_PORTAL_ID', default='')
# HubSpot Field Mapping (JSON string, will be parsed if provided)
_hubspot_field_mapping_str = config('HUBSPOT_FIELD_MAPPING', default='{}')
try:
    import json
    HUBSPOT_FIELD_MAPPING = json.loads(_hubspot_field_mapping_str) if _hubspot_field_mapping_str else {}
except (json.JSONDecodeError, ValueError):
    HUBSPOT_FIELD_MAPPING = {}

# Salesforce Configuration
SALESFORCE_USERNAME = config('SALESFORCE_USERNAME', default='')
SALESFORCE_PASSWORD = config('SALESFORCE_PASSWORD', default='')
SALESFORCE_SECURITY_TOKEN = config('SALESFORCE_SECURITY_TOKEN', default='')
SALESFORCE_SANDBOX = config('SALESFORCE_SANDBOX', default=False, cast=bool)

# Pipedrive Configuration
PIPEDRIVE_API_TOKEN = config('PIPEDRIVE_API_TOKEN', default='')
PIPEDRIVE_BASE_URL = config('PIPEDRIVE_BASE_URL', default='https://api.pipedrive.com/v1')

# Analytics Configuration
ANALYTICS_REQUIRE_CONSENT = config('ANALYTICS_REQUIRE_CONSENT', default=True, cast=bool)
ANALYTICS_EXCLUDED_PATHS = [
    '/admin/',
    '/api/admin/',
    '/static/',
    '/media/',
    '/favicon.ico',
]
ANALYTICS_EXCLUDE_STAFF = config('ANALYTICS_EXCLUDE_STAFF', default=True, cast=bool)
ANALYTICS_USE_BATCH = config('ANALYTICS_USE_BATCH', default=True, cast=bool)
ANALYTICS_BATCH_SIZE = config('ANALYTICS_BATCH_SIZE', default=50, cast=int)
ANALYTICS_BATCH_TIMEOUT = config('ANALYTICS_BATCH_TIMEOUT', default=5, cast=int)  # seconds
ANALYTICS_SESSION_TIMEOUT = config('ANALYTICS_SESSION_TIMEOUT', default=1800, cast=int)  # 30 minutes
ANALYTICS_ENABLE_GEOLOCATION = config('ANALYTICS_ENABLE_GEOLOCATION', default=False, cast=bool)

# External Analytics
ANALYTICS_EXTERNAL_ENABLED = config('ANALYTICS_EXTERNAL_ENABLED', default=False, cast=bool)
GA4_MEASUREMENT_ID = config('GA4_MEASUREMENT_ID', default='')
GA4_API_SECRET = config('GA4_API_SECRET', default='')
MIXPANEL_TOKEN = config('MIXPANEL_TOKEN', default='')

# Webhook Configuration
WEBHOOK_ENABLED = config('WEBHOOK_ENABLED', default=True, cast=bool)
WEBHOOK_SECRET_KEY = config('WEBHOOK_SECRET_KEY', default='')
WEBHOOK_RETRY_ATTEMPTS = config('WEBHOOK_RETRY_ATTEMPTS', default=3, cast=int)
WEBHOOK_RETRY_DELAY = config('WEBHOOK_RETRY_DELAY', default=60, cast=int)

# A/B Testing Configuration
AB_TESTING_ENABLED = config('AB_TESTING_ENABLED', default=True, cast=bool)

# GDPR Configuration
GDPR_DATA_RETENTION_DEFAULT_DAYS = config('GDPR_DATA_RETENTION_DEFAULT_DAYS', default=365, cast=int)
GDPR_ANONYMIZE_ON_DELETE_DEFAULT = config('GDPR_ANONYMIZE_ON_DELETE_DEFAULT', default=True, cast=bool)

# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_TASK_ALWAYS_EAGER = config('CELERY_TASK_ALWAYS_EAGER', default=False, cast=bool)
CELERY_TASK_EAGER_PROPAGATES = config('CELERY_TASK_EAGER_PROPAGATES', default=True, cast=bool)
CELERY_TIMEZONE = config('CELERY_TIMEZONE', default='UTC')
CELERY_ENABLE_UTC = config('CELERY_ENABLE_UTC', default=True, cast=bool)

# Celery Beat Schedule
CELERY_BEAT_SCHEDULE = {
    'retry-failed-webhooks': {
        'task': 'apps.integrations.tasks.retry_failed_webhooks',
        'schedule': 300.0,  # Every 5 minutes
    },
    'update-ab-test-stats': {
        'task': 'apps.integrations.tasks.update_ab_test_stats',
        'schedule': 3600.0,  # Every hour
    },
    'apply-data-retention-policies': {
        'task': 'apps.integrations.tasks.apply_data_retention_policies',
        'schedule': 86400.0,  # Daily
    },
}
