# Generated by Django 4.2.27 on 2025-12-07 13:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('contact_submission', 'Contact Submission'), ('waitlist_join', 'Waitlist Join'), ('lead_created', 'Lead Created'), ('lead_qualified', 'Lead Qualified'), ('lead_converted', 'Lead Converted'), ('newsletter_subscribe', 'Newsletter Subscribe'), ('conversion', 'Conversion')], max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('secret_key', models.CharField(help_text='Secret key for signature verification', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('retry_attempts', models.IntegerField(default=3, help_text='Number of retry attempts on failure')),
                ('retry_delay', models.IntegerField(default=60, help_text='Delay between retries in seconds')),
                ('timeout', models.IntegerField(default=30, help_text='Request timeout in seconds')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Additional headers to include')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Configuration',
                'verbose_name_plural': 'Webhook Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('signature', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='webhooks.webhookconfig')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='webhooks_we_status_81f5e0_idx'), models.Index(fields=['webhook_config', 'created_at'], name='webhooks_we_webhook_d79e20_idx')],
            },
        ),
    ]
