# Generated by Django 4.2.27 on 2025-12-07 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('subscription_status', models.CharField(choices=[('subscribed', 'Subscribed'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained')], default='subscribed', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website'), ('popup', 'Popup'), ('footer', 'Footer'), ('checkout', 'Checkout'), ('landing_page', 'Landing Page'), ('social_media', 'Social Media'), ('referral', 'Referral'), ('other', 'Other')], default='website', max_length=50)),
                ('interests', models.JSONField(blank=True, default=list, help_text='List of interest tags')),
                ('preference', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('consent_text', models.TextField(blank=True, help_text='Text of consent agreement', null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_reason', models.TextField(blank=True, null=True)),
                ('unsubscribe_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('bounce_count', models.IntegerField(default=0)),
                ('last_bounce_at', models.DateTimeField(blank=True, null=True)),
                ('bounce_reason', models.TextField(blank=True, null=True)),
                ('complaint_count', models.IntegerField(default=0)),
                ('last_complaint_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
