# Generated by Django 4.2.27 on 2025-12-07 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('lead_source', models.CharField(choices=[('organic', 'Organic'), ('paid_ad', 'Paid Ad'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('email_campaign', 'Email Campaign'), ('website', 'Website')], default='website', max_length=50)),
                ('lead_score', models.IntegerField(default=0, help_text='Score from 0-100')),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('lifecycle_stage', models.CharField(choices=[('visitor', 'Visitor'), ('lead', 'Lead'), ('marketing_qualified', 'Marketing Qualified'), ('sales_qualified', 'Sales Qualified'), ('customer', 'Customer')], default='lead', max_length=30)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
