# Generated by Django 4.2.27 on 2025-12-07 10:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('page_url', models.URLField()),
                ('page_title', models.CharField(blank=True, max_length=500, null=True)),
                ('referrer_url', models.URLField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('other', 'Other')], max_length=20, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration', models.FloatField(blank=True, help_text='Time on page in seconds', null=True)),
                ('is_exit_page', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session_id', '-timestamp'], name='analytics_p_session_57683f_idx'), models.Index(fields=['-timestamp'], name='analytics_p_timesta_b589d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_index=True, max_length=200)),
                ('event_category', models.CharField(choices=[('user_interaction', 'User Interaction'), ('form', 'Form'), ('navigation', 'Navigation'), ('media', 'Media'), ('download', 'Download'), ('other', 'Other')], default='other', max_length=50)),
                ('event_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('event_properties', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('page_url', models.URLField(blank=True, null=True)),
                ('user_identifier', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_name', '-timestamp'], name='analytics_e_event_n_142ba1_idx'), models.Index(fields=['session_id', '-timestamp'], name='analytics_e_session_55fd3a_idx'), models.Index(fields=['-timestamp'], name='analytics_e_timesta_28085e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversion_type', models.CharField(choices=[('form_submission', 'Form Submission'), ('signup', 'Signup'), ('purchase', 'Purchase'), ('download', 'Download'), ('newsletter_subscription', 'Newsletter Subscription'), ('waitlist_signup', 'Waitlist Signup'), ('contact_submission', 'Contact Submission'), ('lead_capture', 'Lead Capture'), ('other', 'Other')], db_index=True, max_length=50)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('attribution_data', models.JSONField(blank=True, default=dict, help_text='UTM parameters, referrer, etc.')),
                ('campaign_info', models.JSONField(blank=True, default=dict, help_text='Campaign name, source, medium, etc.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Conversion',
                'verbose_name_plural': 'Conversions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['conversion_type', '-timestamp'], name='analytics_c_convers_4a7def_idx'), models.Index(fields=['-timestamp'], name='analytics_c_timesta_a14730_idx')],
            },
        ),
    ]
