# Generated by Django 4.2.27 on 2025-12-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='ab_test_name',
            field=models.CharField(blank=True, help_text='Name of A/B test', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='ab_test_variant',
            field=models.CharField(blank=True, help_text='A/B test variant (A or B)', max_length=1, null=True),
        ),
    ]
